CREATE TABLE IF NOT EXISTS User (
    id IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(16) NOT NULL,
    addressId BIGINT
);

CREATE TABLE IF NOT EXISTS Address (
    id IDENTITY NOT NULL PRIMARY KEY,
    address VARCHAR(80) NOT NULL
);
