/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You should have received a copy of  the license along with this library.
 * You may also obtain a copy of the License at
 *         http://www.apache.org/licenses/LICENSE-2.0.
 */
package sf.wicklet.dsl.css.impl;

import sf.wicklet.dsl.css.api.IDeclaration;

public enum PK {
	Animation("animation"),
	AnimationDelay("animation-delay"),
	AnimationDirection("animation-direction"),
	AnimationDuration("animation-duration"),
	AnimationIterationCount("animation-iteration-count"),
	AnimationName("animation-name"),
	AnimationPlayState("animation-play-state"),
	AnimationTimingFunction("animation-timing-function"),
	Appearance("appearance"),
	AspectRatio("aspect-ratio"),
	Azimuth("azimuth"),
	BackfaceVisibility("backface-visibility"),
	Background("background"),
	BackgroundAttachment("background-attachment"),
	BackgroundClip("background-clip"),
	BackgroundColor("background-color"),
	BackgroundImage("background-image"),
	BackgroundOrigin("background-origin"),
	BackgroundPosition("background-position"),
	BackgroundRepeat("background-repeat"),
	BackgroundSize("background-size"),
	Border("border"),
	BorderBottom("border-bottom"),
	BorderBottomColor("border-bottom-color"),
	BorderBottomLeftRadius("border-bottom-left-radius"),
	BorderBottomRightRadius("border-bottom-right-radius"),
	BorderBottomStyle("border-bottom-style"),
	BorderBottomWidth("border-bottom-width"),
	BorderCollapse("border-collapse"),
	BorderColor("border-color"),
	BorderImage("border-image"),
	BorderImageOutside("border-image-outside"),
	BorderImageRepeat("border-image-repeat"),
	BorderImageSlice("border-image-slice"),
	BorderImageSource("border-image-source"),
	BorderImageWidth("border-image-width"),
	BorderLeft("border-left"),
	BorderLeftColor("border-left-color"),
	BorderLeftStyle("border-left-style"),
	BorderLeftWidth("border-left-width"),
	BorderRadius("border-radius"),
	BorderRight("border-right"),
	BorderRightColor("border-right-color"),
	BorderRightStyle("border-right-style"),
	BorderRightWidth("border-right-width"),
	BorderSpacing("border-spacing"),
	BorderStyle("border-style"),
	BorderTop("border-top"),
	BorderTopColor("border-top-color"),
	BorderTopLeftRadius("border-top-left-radius"),
	BorderTopRightRadius("border-top-right-radius"),
	BorderTopStyle("border-top-style"),
	BorderTopWidth("border-top-width"),
	BorderWidth("border-width"),
	Bottom("bottom"),
	BoxDecorationBreak("box-decoration-break"),
	BoxShadow("box-shadow"),
	BoxSizing("box-sizing"),
	BreakAfter("break-after"),
	BreakBefore("break-before"),
	BreakInside("break-inside"),
	CaptionSide("caption-side"),
	Clear("clear"),
	Clip("clip"),
	Color("color"),
	ColorIndex("color-index"),
	ColumnCount("column-count"),
	ColumnFill("column-fill"),
	ColumnGap("column-gap"),
	ColumnRule("column-rule"),
	ColumnSpan("column-span"),
	ColumnWidth("column-width"),
	Columns("columns"),
	Content("content"),
	CounterIncrement("counter-increment"),
	CounterReset("counter-reset"),
	Cue("cue"),
	CueAfter("cue-after"),
	CueBefore("cue-before"),
	Cursor("cursor"),
	DeviceAspectRatio("device-aspect-ratio"),
	DeviceHeight("device-height"),
	DeviceWidth("device-width"),
	Direction("direction"),
	Display("display"),
	Elevation("elevation"),
	EmptyCells("empty-cells"),
	Flex("flex"),
	FlexAlign("flex-align"),
	FlexDirection("flex-direction"),
	FlexFlow("flex-flow"),
	FlexItemAlign("flex-item-align"),
	FlexLinePack("flex-line-pack"),
	FlexOrder("flex-order"),
	FlexPack("flex-pack"),
	FlexWrap("flex-wrap"),
	Float("float"),
	FlowFrom("flow-from"),
	FlowInto("flow-into"),
	Font("font"),
	FontFamily("font-family"),
	FontFeatureSettings("font-feature-settings"),
	FontSize("font-size"),
	FontSizeAdjust("font-size-adjust"),
	FontStretch("font-stretch"),
	FontStyle("font-style"),
	FontVariant("font-variant"),
	FontWeight("font-weight"),
	Grid("grid"),
	GridCell("grid-cell"),
	GridColumn("grid-column"),
	GridColumnAlign("grid-column-align"),
	GridColumnSizing("grid-column-sizing"),
	GridColumnSpan("grid-column-span"),
	GridColumns("grid-columns"),
	GridFlow("grid-flow"),
	GridRow("grid-row"),
	GridRowAlign("grid-row-align"),
	GridRowSizing("grid-row-sizing"),
	GridRowSpan("grid-row-span"),
	GridRows("grid-rows"),
	GridTemplate("grid-template"),
	HangingPunctuation("hanging-punctuation"),
	Height("height"),
	HhyphenateCharacter("hyphenate-character"),
	HyphenateCharacter("hyphenate-character"),
	HyphenateLimitChars("hyphenate-limit-chars"),
	HyphenateLimitLast("hyphenate-limit-last"),
	HyphenateLimitLines("hyphenate-limit-lines"),
	HyphenateLimitZone("hyphenate-limit-zone"),
	Hyphens("hyphens"),
	Icon("icon"),
	ImageOrientation("image-orientation"),
	InterpretAs("interpret-as"),
	Left("left"),
	LetterSpacing("letter-spacing"),
	LineHeight("line-height"),
	ListStyle("list-style"),
	ListStyleImage("list-style-image"),
	ListStylePosition("list-style-position"),
	ListStyleType("list-style-type"),
	Margin("margin"),
	MarginBottom("margin-bottom"),
	MarginLeft("margin-left"),
	MarginRight("margin-right"),
	MarginTop("margin-top"),
	Mark("mark"),
	MarkAfter("mark-after"),
	MarkBefore("mark-before"),
	MarkerOffset("marker-offset"),
	Marks("marks"),
	MarqueeDirection("marquee-direction"),
	MarqueePlayCount("marquee-play-count"),
	MarqueeSpeed("marquee-speed"),
	MarqueeStyle("marquee-style"),
	MaxHeight("max-height"),
	MaxWidth("max-width"),
	MinHeight("min-height"),
	MinWidth("min-width"),
	Monochrome("monochrome"),
	NavDown("nav-down"),
	NavIndex("nav-index"),
	NavLeft("nav-left"),
	NavRight("nav-right"),
	NavUp("nav-up"),
	ObjectFit("object-fit"),
	ObjectPosition("object-position"),
	Opacity("opacity"),
	Orientation("orientation"),
	Orphans("orphans"),
	Outline("outline"),
	OutlineColor("outline-color"),
	OutlineOffset("outline-offset"),
	OutlineStyle("outline-style"),
	OutlineWidth("outline-width"),
	Overflow("overflow"),
	OverflowStyle("overflow-style"),
	OverflowX("overflow-x"),
	OverflowY("overflow-y"),
	Padding("padding"),
	PaddingBottom("padding-bottom"),
	PaddingLeft("padding-left"),
	PaddingRight("padding-right"),
	PaddingTop("padding-top"),
	Page("page"),
	PageBreakAfter("page-break-after"),
	PageBreakBefore("page-break-before"),
	PageBreakInside("page-break-inside"),
	Pause("pause"),
	PauseAfter("pause-after"),
	PauseBefore("pause-before"),
	Perspective("perspective"),
	PerspectiveOrigin("perspective-origin"),
	Phonemes("phonemes"),
	Pitch("pitch"),
	PitchRange("pitch-range"),
	PlayDuring("play-during"),
	Position("position"),
	Positioning("Positioning"),
	PunctuationTrim("punctuation-trim"),
	Quotes("quotes"),
	RegionOverflow("region-overflow"),
	Resize("resize"),
	Resolution("resolution"),
	Rest("rest"),
	RestAfter("rest-after"),
	RestBefore("rest-before"),
	Richness("richness"),
	Right("right"),
	RubyAlign("ruby-align"),
	RubyOverhang("ruby-overhang"),
	RubyPosition("ruby-position"),
	RubySpan("ruby-span"),
	Scan("scan"),
	ShapeImageThreshold("shape-image-threshold"),
	ShapeImageThresholdmargin("shape-image-thresholdmargin"),
	ShapeInside("shape-inside"),
	ShapeOutside("shape-outside"),
	Size("size"),
	Speak("speak"),
	SpeakHeader("speak-header"),
	SpeakNumeral("speak-numeral"),
	SpeakPunctuation("speak-punctuation"),
	SpeechRate("speech-rate"),
	Stress("stress"),
	TableLayout("table-layout"),
	Tables("Tables"),
	TextAlign("text-align"),
	TextAlignLast("text-align-last"),
	TextCombine("text-combine"),
	TextDecoration("text-decoration"),
	TextDecorationColor("text-decoration-color"),
	TextDecorationLine("text-decoration-line"),
	TextDecorationSkip("text-decoration-skip"),
	TextDecorationStyle("text-decoration-style"),
	TextEmphasis("text-emphasis"),
	TextIndent("text-indent"),
	TextJustify("text-justify"),
	TextOutline("text-outline"),
	TextOverflow("text-overflow"),
	TextShadow("text-shadow"),
	TextTransform("text-transform"),
	TextUnderlinePosition("text-underline-position"),
	TextWrap("text-wrap"),
	Top("top"),
	Transform("transform"),
	TransformOrigin("transform-origin"),
	TransformStyle("transform-style"),
	Transition("transition"),
	TransitionDelay("transition-delay"),
	TransitionDuration("transition-duration"),
	TransitionProperty("transition-property"),
	TransitionTimingFunction("transition-timing-function"),
	UnicodeBidi("unicode-bidi"),
	VerticalAlign("vertical-align"),
	Visibility("visibility"),
	VoiceBalance("voice-balance"),
	VoiceDuration("voice-duration"),
	VoiceFamily("voice-family"),
	VoicePitch("voice-pitch"),
	VoicePitchRange("voice-pitch-range"),
	VoiceRate("voice-rate"),
	VoiceStress("voice-stress"),
	VoiceVolume("voice-volume"),
	Volume("volume"),
	WhiteSpace("white-space"),
	Widows("widows"),
	Width("width"),
	WordBreak("word-break"),
	WordSpacing("word-spacing"),
	WordWrap("word-wrap"),
	Wrap("wrap"),
	WrapFlow("wrap-flow"),
	WrapMargin("wrap-margin"),
	WrapPadding("wrap-padding"),
	WrapThrough("wrap-through"),
	WritingMode("writing-mode"),
	ZIndex("z-index"),
	// Mozilla extensions
	MozAnimation("-moz-animation"),
	MozAnimationDelay("-moz-animation-delay"),
	MozAnimationDirection("-moz-animation-direction"),
	MozAnimationDuration("-moz-animation-duration"),
	MozAnimationFillMode("-moz-animation-fill-mode"),
	MozAnimationIterationCount("-moz-animation-iteration-count"),
	MozAnimationName("-moz-animation-name"),
	MozAnimationPlayState("-moz-animation-play-state"),
	MozAnimationTimingFunction("-moz-animation-timing-function"),
	MozAppearance("-moz-appearance"),
	MozBackfaceVisibility("-moz-backface-visibility"),
	MozBackgroundInlinePolicy("-moz-background-inline-policy"),
	MozBorderImage("-moz-border-image"),
	MozBorderImageOutset("-moz-border-image-outset"),
	MozBorderImageRepeat("-moz-border-image-repeat"),
	MozBorderImageSlice("-moz-border-image-slice"),
	MozBorderImageSource("-moz-border-image-source"),
	MozBorderImageWidth("-moz-border-image-width"),
	MozBoxSizing("-moz-box-sizing"),
	MozClipPath("clip-path"),
	MozColumnCount("-moz-column-count"),
	MozColumnFill("-moz-column-fill"),
	MozColumnGap("-moz-column-gap"),
	MozColumnWidth("-moz-column-width"),
	MozColumnRule("-moz-column-rule"),
	MozColumnRuleWidth("-moz-column-rule-width"),
	MozColumnRuleStyle("-moz-column-rule-style"),
	MozColumnRuleColor("-moz-column-rule-color"),
	MozFilter("filter"),
	MozFontFeatureSettings("-moz-font-feature-settings"),
	MozFontLanguageOverride("-moz-font-language-override"),
	MozHyphens("-moz-hyphens"),
	MozMask("mask"),
	MozPerspective("-moz-perspective"),
	MozPerspectiveOrigin("-moz-perspective-origin"),
	MozPointerEvents("pointer-events"),
	MozTextAlignLast("-moz-text-align-last"),
	MozTextDecorationColor("-moz-text-decoration-color"),
	MozTextDecorationLine("-moz-text-decoration-line"),
	MozTextDecorationStyle("-moz-text-decoration-style"),
	MozTransform("-moz-transform"),
	MozTransformOrigin("-moz-transform-origin"),
	MozTransformStyle("-moz-transform-style"),
	MozTransition("-moz-transition"),
	MozTransitionDelay("-moz-transition-delay"),
	MozTransitionDuration("-moz-transition-duration"),
	MozTransitionProperty("-moz-transition-property"),
	MozTransitionTimingFunction("-moz-transition-timing-function"),
	// Mozilla extensions with standard counterpart.
	MozBackgroundClip("-moz-background-clip"),
	MozBackgroundOrigin("-moz-background-origin"),
	MozBackgroundSize("-moz-background-size"),
	MozOpacity("-moz-opacity"),
	MozOutline("-moz-outline"),
	MozOutlineColor("-moz-outline-color"),
	MozOutlineOffset("-moz-outline-offset"),
	MozOutlineStyle("-moz-outline-style"),
	MozOutlineWidth("-moz-outline-width"),
	// Webkit extensions
	WebkitAnimation("-webkit-animation"),
	WebkitAnimationDelay("-webkit-animation-delay"),
	WebkitAnimationDirection("-webkit-animation-direction"),
	WebkitAnimationDuration("-webkit-animation-duration"),
	WebkitAnimationFillMode("-webkit-animation-fill-mode"),
	WebkitAnimationIterationCount("-webkit-animation-iteration-count"),
	WebkitAnimationName("-webkit-animation-name"),
	WebkitAnimationPlayState("-webkit-animation-play-state"),
	WebkitAnimationTimingFunction("-webkit-animation-timing-function"),
	WebkitAppearance("-webkit-appearance"),
	WebkitBackfaceVisibility("-webkit-backface-visibility"),
	WebkitBorderImage("-webkit-border-image"),
	WebkitColumnCount("-webkit-column-count"),
	WebkitColumnGap("-webkit-column-gap"),
	WebkitColumnWidth("-webkit-column-width"),
	WebkitColumnRule("-webkit-column-rule"),
	WebkitColumnRuleWidth("-webkit-column-rule-width"),
	WebkitColumnRuleStyle("-webkit-column-rule-style"),
	WebkitColumnRuleColor("-webkit-column-rule-color"),
	WebkitColumns("-webkit-columns"),
	WebkitColumnSpan("-webkit-column-span"),
	WebkitFontFeatureSettings("-webkit-font-feature-settings"),
	WebkitFontKerning("-webkit-font-kerning"),
	WebkitFontSizeDelta("-webkit-font-size-delta"),
	WebkitFontVariantLigatures("-webkit-font-variant-ligatures"),
	WebkitGridColumn("-webkit-grid-column"),
	WebkitGridColumns("-webkit-grid-columns"),
	WebkitGridRow("-webkit-grid-row"),
	WebkitGridRows("-webkit-grid-rows"),
	WebkitHyphens("-webkit-hyphens"),
	WebkitPerspective("-webkit-perspective"),
	WebkitPerspectiveOrigin("-webkit-perspective-origin"),
	WebkitRegionOverflow("-webkit-region-overflow"),
	WebkitTransform("-webkit-transform"),
	WebkitTransformOrigin("-webkit-transform-origin"),
	WebkitTransformStyle("-webkit-transform-style"),
	WebkitTransition("-webkit-transition"),
	WebkitTransitionDelay("-webkit-transition-delay"),
	WebkitTransitionDuration("-webkit-transition-duration"),
	WebkitTransitionProperty("-webkit-transition-property"),
	WebkitTransitionTimingFunction("-webkit-transition-timing-function"),
	// Webkit extensions with standard counterpart.
	WebkitBackgroundClip("-webkit-background-clip"),
	WebkitBackgroundOrigin("-webkit-background-origin"),
	WebkitBackgroundSize("-webkit-background-size"),
	WebkitBorderBottomLeftRadius("-webkit-border-bottom-left-radius"),
	WebkitBorderBottomRightRadius("-webkit-border-bottom-right-radius"),
	WebkitBorderRadius("-webkit-border-radius"),
	WebkitBorderTopLeftRadius("-webkit-border-top-left-radius"),
	WebkitBorderTopRightRadius("-webkit-border-top-right-radius"),
	WebkitBoxSizing("-webkit-box-sizing"),
	WebkitOpacity("-webkit-opacity"),
	// Microsoft extensions
	MsAccelerator("-ms-accelerator"),
	MsAnimation("-ms-animation"),
	MsAnimationDelay("-ms-animation-delay"),
	MsAnimationDirection("-ms-animation-direction"),
	MsAnimationDuration("-ms-animation-duration"),
	MsAnimationFillMode("-ms-animation-fill-mode"),
	MsAnimationIterationCount("-ms-animation-iteration-count"),
	MsAnimationName("-ms-animation-name"),
	MsAnimationPlayState("-ms-animation-play-state"),
	MsAnimationTimingFunction("-ms-animation-timing-function"),
	MsBackfaceVisibility("-ms-backface-visibility"),
	MsBackgroundPositionX("-ms-background-position-x"),
	MsBackgroundPositionY("-ms-background-position-y"),
	MsBehavior("-ms-behavior"),
	MsBlockProgression("-ms-block-progression"),
	MsBoxAlign("-ms-box-align"),
	MsBoxDirection("-ms-box-direction"),
	MsBoxFlex("-ms-box-flex"),
	MsBoxLineProgression("-ms-box-line-progression"),
	MsBoxLines("-ms-box-lines"),
	MsBoxOrdinalGroup("-ms-box-ordinal-group"),
	MsBoxOrient("-ms-box-orient"),
	MsBoxPack("-ms-box-pack"),
	MsContentZoomBoundary("-ms-content-zoom-boundary"),
	MsContentZoomBoundaryMax("-ms-content-zoom-boundary-max"),
	MsContentZoomBoundaryMin("-ms-content-zoom-boundary-min"),
	MsContentZoomChaining("-ms-content-zoom-chaining"),
	MsContentZoomSnap("-ms-content-zoom-snap"),
	MsContentZoomSnapPoints("-ms-content-zoom-snap-points"),
	MsContentZoomSnapType("-ms-content-zoom-snap-type"),
	MsContentZooming("-ms-content-zooming"),
	MsFilter("-ms-filter"),
	MsFlowFrom("-ms-flow-from"),
	MsFlowInto("-ms-flow-into"),
	MsFontFeatureSettings("-ms-font-feature-settings"),
	MsGridColumn("-ms-grid-column"),
	MsGridColumnAlign("-ms-grid-column-align"),
	MsGridColumnSpan("-ms-grid-column-span"),
	MsGridColumns("-ms-grid-columns"),
	MsGridLayer("-ms-grid-layer"),
	MsGridRow("-ms-grid-row"),
	MsGridRowAlign("-ms-grid-row-align"),
	MsGridRowSpan("-ms-grid-row-span"),
	MsGridRows("-ms-grid-rows"),
	MsHighContrastAdjust("-ms-high-contrast-adjust"),
	MsHyphenateLimitChars("-ms-hyphenate-limit-chars"),
	MsHyphenateLimitLines("-ms-hyphenate-limit-lines"),
	MsHyphenateLimitZone("-ms-hyphenate-limit-zone"),
	MsHyphens("-ms-hyphens"),
	MsImeMode("-ms-ime-mode"),
	MsInterpolationMode("-ms-interpolation-mode"),
	MsLayoutFlow("-ms-layout-flow"),
	MsLayoutGrid("-ms-layout-grid"),
	MsLayoutGridChar("-ms-layout-grid-char"),
	MsLayoutGridLine("-ms-layout-grid-line"),
	MsLayoutGridMode("-ms-layout-grid-mode"),
	MsLayoutGridType("-ms-layout-grid-type"),
	MsLineBreak("-ms-line-break"),
	MsOverflowStyle("-ms-overflow-style"),
	MsOverflowX("-ms-overflow-x"),
	MsOverflowY("-ms-overflow-y"),
	MsPerspective("-ms-perspective"),
	MsPerspectiveOrigin("-ms-perspective-origin"),
	MsPerspectiveOriginX("-ms-perspective-origin-x"),
	MsPerspectiveOriginY("-ms-perspective-origin-y"),
	MsScrollBoundary("-ms-scroll-boundary"),
	MsScrollBoundaryBottom("-ms-scroll-boundary-bottom"),
	MsScrollBoundaryLeft("-ms-scroll-boundary-left"),
	MsScrollBoundaryRight("-ms-scroll-boundary-right"),
	MsScrollBoundaryTop("-ms-scroll-boundary-top"),
	MsScrollChaining("-ms-scroll-chaining"),
	MsScrollRails("-ms-scroll-rails"),
	MsScrollSnapPointsX("-ms-scroll-snap-points-x"),
	MsScrollSnapPointsY("-ms-scroll-snap-points-y"),
	MsScrollSnapType("-ms-scroll-snap-type"),
	MsScrollSnapX("-ms-scroll-snap-x"),
	MsScrollSnapY("-ms-scroll-snap-y"),
	MsScrollbarArrowColor("-ms-scrollbar-arrow-color"),
	MsScrollbarBaseColor("-ms-scrollbar-base-color"),
	MsScrollbarDarkshadowColor("-ms-scrollbar-darkshadow-color"),
	MsScrollbarFaceColor("-ms-scrollbar-face-color"),
	MsScrollbarHighlightColor("-ms-scrollbar-highlight-color"),
	MsScrollbarShadowColor("-ms-scrollbar-shadow-color"),
	MsScrollbarTrackColor("-ms-scrollbar-track-color"),
	MsTextAlignLast("-ms-text-align-last"),
	MsTextAutospace("-ms-text-autospace"),
	MsTextJustify("-ms-text-justify"),
	MsTextKashidaSpace("-ms-text-kashida-space"),
	MsTextOverflow("-ms-text-overflow"),
	MsTextSizeAdjust("-ms-text-size-adjust"),
	MsTextUnderlinePosition("-ms-text-underline-position"),
	MsTouchAction("-ms-touch-action"),
	MsTransform("-ms-transform"),
	MsTransformOrigin("-ms-transform-origin"),
	MsTransformOriginX("-ms-transform-origin-x"),
	MsTransformOriginY("-ms-transform-origin-y"),
	MsTransformOriginZ("-ms-transform-origin-z"),
	MsTransformStyle("-ms-transform-style"),
	MsTransition("-ms-transition"),
	MsTransitionDelay("-ms-transition-delay"),
	MsTransitionDuration("-ms-transition-duration"),
	MsTransitionProperty("-ms-transition-property"),
	MsTransitionTimingFunction("-ms-transition-timing-function"),
	MsUserSelect("-ms-user-select"),
	MsWordBreak("-ms-word-break"),
	MsWordWrap("-ms-word-wrap"),
	MsWrapFlow("-ms-wrap-flow"),
	MsWrapMargin("-ms-wrap-margin"),
	MsWrapThrough("-ms-wrap-through"),
	MsWritingMode("-ms-writing-mode"),
	MsZoom("-ms-zoom"),
	// Misc extensions
	EpubCaptionSide("-epub-caption-side"),
	EpubHyphens("-epub-hyphens"),
	EpubTextCombine("-epub-text-combine"),
	EpubTextEmphasis("-epub-text-emphasis"),
	EpubTextEmphasisColor("-epub-text-emphasis-color"),
	EpubTextEmphasisStyle("-epub-text-emphasis-style"),
	EpubTextOrientation("-epub-text-orientation"),
	EpubTextTransform("-epub-text-transform"),
	EpubWordBreak("-epub-word-break"),
	EpubWritingMode("-epub-writing-mode"),
	WapAccesskey("-wap-accesskey"),
	WapInputFormat("-wap-input-format"),
	WapInputRequired("-wap-input-required"),
	WapMarqueeDir("-wap-marquee-dir"),
	WapMarqueeLoop("-wap-marquee-loop"),
	WapMarqueeSpeed("-wap-marquee-speed"),
	WapMarqueeStyle("-wap-marquee-style"),
	//
	;

	private String name;

	private PK(final String name) {
		this.name = name;
	}

	public IDeclaration set(final Object expr) {
		return s(expr);
	}

	public IDeclaration set(final String expr) {
		return s(expr);
	}

	public IDeclaration set(final boolean expr) {
		return s(expr);
	}

	public IDeclaration set(final int expr) {
		return s(expr);
	}

	public IDeclaration set(final double expr) {
		return s(expr);
	}

	public IDeclaration setf(final String format, final Object...args) {
		return new Declaration(name, String.format(format, args));
	}

	/** Set value, shorthand for set(). */
	public IDeclaration s(final Object expr) {
		return new Declaration(name, expr);
	}

	/** Set value, shorthand for set(). */
	public IDeclaration s(final String expr) {
		return new Declaration(name, expr);
	}

	/** Set value, shorthand for set(). */
	public IDeclaration s(final boolean expr) {
		return new Declaration(name, String.valueOf(expr));
	}

	/** Set value, shorthand for set(). */
	public IDeclaration s(final int expr) {
		return new Declaration(name, String.valueOf(expr));
	}

	/** Set value, shorthand for set(). */
	public IDeclaration s(final double expr) {
		return new Declaration(name, String.valueOf(expr));
	}

	/** Set value, shorthand for setf(). */
	public IDeclaration f(final String format, final Object...args) {
		return new Declaration(name, String.format(format, args));
	}

	/** Set value as &lt;n>px */
	public IDeclaration px(final int n) {
		return set(String.valueOf(n) + "px");
	}

	/** Set value as &lt;n>px */
	public IDeclaration px(final int...a) {
		final StringBuilder b = new StringBuilder();
		for (final int n: a) {
			if (b.length() > 0) {
				b.append(' ');
			}
			b.append(String.valueOf(n));
			b.append("px");
		}
		return set(b);
	}

	/** Set value as &lt;n>em */
	public IDeclaration em(final double n) {
		return set(String.valueOf(n) + "em");
	}

	/** Set value as &lt;n>em */
	public IDeclaration em(final double...a) {
		final StringBuilder b = new StringBuilder();
		for (final double n: a) {
			if (b.length() > 0) {
				b.append(' ');
			}
			b.append(String.valueOf(n));
			b.append("em");
		}
		return set(b);
	}

	@Override
	public String toString() {
		return name;
	}
}
